apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.serviceName }}
  labels:
    name: {{ .Values.service.serviceLabelName }}
    app: {{ .Values.postgres.appName }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.postgres.postgresPort }}
      targetPort: {{ .Values.postgres.postgresPort }}
      nodePort: {{ .Values.service.nodePort }}
  selector:
    name: {{ .Values.postgres.postgresPodName }}
    app: {{ .Values.postgres.appName }}